---
title: "00. Architecture du code"
author: "Meyer, Berleur, Sklenard, Bracq"
date: "08/02/2023"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot{}
- \fancyhead[CO,CE]{Poing Levé}
- \fancyfoot[CO,CE]{Sondage}
- \fancyfoot[R]{\thepage}
output:
  pdf_document:
    toc: yes
    toc_depth : 3
    latex_engine: xelatex
  html_document:
    toc: yes
editor_options: 
  markdown: 
    wrap: sentence
---

```{=html}
<style>
body {
text-align: justify}
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```

Ce document vise à organiser et rassembler tous les fichiers du projet de Statapp concernant les zonages statistiques dans la mesure de la délinquance. 

### Paramètres

### Packages

```{r packages, include=FALSE}
source("01.packages.R")
```


### Bases de données

```{r chargement-base délinquance}
load("C:\\Users\\marie\\OneDrive\\Documents\\cours\\ensae\\stat app\\donnees.secretisees.delinquance.RData") # marie
load("~/Documents/ENSAE/Stats_app/Data/donnees.secretisees.delinquance.RData") #cathu
load("C:/Users/Utilisateur/Desktop/donnees.secretisees.delinquance.RData") #clem
# load("/Users/sklenard/Downloads/donnees.secretisees.delinquance.RData")# Gaby
```

```{r bases de données, include=FALSE}
source("02.bases.R")
```
