---
title: "Cartes"
author: "Meyer, Berleur, Sklenard, Bracq"
date: "07/02/2023"
output: html_document
---
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot{}
- \fancyhead[CO,CE]{Poing Levé}
- \fancyfoot[CO,CE]{Sondage}
- \fancyfoot[R]{\thepage}
output:
  pdf_document:
    toc: yes
    toc_depth : 3
    latex_engine: xelatex
  html_document:
    toc: yes
editor_options: 
  markdown: 
    wrap: sentence
---

```{=html}
<style>
body {
text-align: justify}
</style>
```

On va essayer de faire une carte avec la base créée pour l'ACM.


```{r}
# install.packages('sf')
# install.packages('ggplot2')
#install.packages('ggplot')
library(sf)
library(ggplot2)
#library(ggplot)
sf_use_s2(FALSE) #turns off spherical geometry
```


```{r}

df_facto_carto <- merge(x = df_facto_zon, y = contours, by.x = 'CODGEO', by.y = 'insee')
ggplot() + geom_sf(data = contours)
fr_cont_cropped <- st_crop(contours, xmin = -20, xmax = 40, ymin = 30, ymax = 55)
ggplot() + geom_sf(data = fr_cont_cropped) + theme_bw() + coord_sf(expand = FALSE)


df_facto_carto <- merge(x = df_facto_zon, y = fr_cont_cropped, by.x = 'CODGEO', by.y = 'insee')
```

```{r}
as.numeric(unlist(df_facto_carto))
plot(df_facto_carto)
```




```{r}
plot(df_facto_carto$geometry)
ggplot(df_facto_carto) + geom_sf()
```





