---
title: "Statistiques descriptives - base complète"
author: "Bracq, Meyer, Sklenard, Berleur"
date: "2023-01-25"
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead{}
- \fancyfoot{}
- \fancyhead[CO,CE]{Poing Levé}
- \fancyfoot[CO,CE]{Sondage}
- \fancyfoot[R]{\thepage}
output:
  pdf_document:
    toc: yes
    toc_depth : 3
    latex_engine: xelatex
  html_document:
    toc: yes
editor_options: 
  markdown: 
    wrap: sentence
---

```{=html}
<style>
body {
text-align: justify}
</style>
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```


Maintenant on va créer des sous-bases par type de délinquance (variable classe) et par année (on enlève 2020 et 2021).


```{r fonction-découpage}
df_1619 <- subset(t.del, t.del$annee %in% c(2016, 2017, 2018, 2019)) #on sélectionne les années

decoupage_classe_merge <- function(classe_del) {
  df1 <- subset(df_1619, df_1619$classe == classe_del) #on sélectionne un type de délinquance
  df_long <- melt(data = df1, id.vars=c('id',"annee","duree_debut_fait_date_enregistrement","classe","dept_serv"),variable.name='info commune', value.name='commune') # format wide to long
  df_long['info commune'] <- as.character(df_long['info commune'])
  df_long <- as_tibble(df_long)
  df_geo <- merge(x=contours,y=df_long, by.x='insee',by.y='commune', all.y=TRUE) #jointure avec les contours géo
  df_geo$insee = str_remove(df_geo$insee, "^0+") #pr avoir le même format que zonages
  df_merged <- merge(x=df_geo, y=zonages, by.x='insee', by.y='CODGEO', all.x=TRUE) #jointure avec les zonages insee
  df_merged <- as_tibble(df_merged)
  saveRDS(df_merged, file = paste(paste('del_merged',classe_del,sep = "_"),'rds',sep='.')) # on enregistre le sous df correspondant
}


liste_classe <- unique(t.del$classe) # on récupère une liste de toutes les classes de délinquance
lapply(liste_classe, decoupage_classe_merge) # on applique la fonction à chaque classe pour créer le df correspondant
```



(code en dehors de la fonction si besoin ... :)
On transforme le df en format long pour avoir une colonne 'info commune' (infraction, mec ou victime) et une colonne 'commune'
```{r wide_to_long}
t.del.A <- readRDS("del_merged_A.rds")
t.del.A_long <- melt(data = t.del.A, id.vars=c('id',"annee","duree_debut_fait_date_enregistrement","classe","dept_serv"),variable.name='info commune', value.name='commune')
t.del.A_long <- as_tibble(t.del.A_long)
```

On merge avec les contours géo et les zonages de l'insee !!
```{r jointures}
t.del.A_geo <- merge(x=contours,y=t.del.A_long, by.x='insee',by.y='commune', all.y=TRUE)
t.del.A_geo$insee = str_remove(t.del.A_geo$insee, "^0+")
t.del.A_merged <- merge(x=t.del.A_geo, y=zonages, by.x='insee', by.y='CODGEO', all.x=TRUE)
t.del.A_merged <- as_tibble(t.del.A_merged)
saveRDS(t.del.A_merged, file = "del_merged_A.rds")

```

